### ISSUE TITLE
Help!No such file or directory ../../instances_trainval2014.json

### ISSUE THREAD

**Issue by lzw0515** [Duankaiwen/CenterNet#109]
when I use python train.py CenterNet-104,I got the error.
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "train.py", line 193, in <listcomp>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "/home/zhouwei_lou/CenterNet-master/db/coco.py", line 68, in __init__
    self._load_data()
  File "/home/zhouwei_lou/CenterNet-master/db/coco.py", line 79, in _load_data
    self._extract_data()
  File "/home/zhouwei_lou/CenterNet-master/db/coco.py", line 110, in _extract_data
    self._coco    = COCO(self._label_file)
  File "data/coco/PythonAPI/pycocotools/coco.py", line 86, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '../data/coco/annotations/instances_trainval2014.json'

I check the file, anybody who solved this probiem before?

**Comment by lzw0515** [comment]
@Duankaiwen

**Comment by lzw0515** [comment]
I have solved the problem

**Comment by KelvinHuang666** [comment]
how did U solve it???I meet the same problem,Thanks

**Comment by KelvinHuang666** [comment]
how did U solve it???I meet the same problem,Thanks

**Comment by KelvinHuang666** [comment]
how did U solve it???I meet the same problem,Thanks

**Comment by lzw0515** [comment]
> how did U solve it???I meet the same problem,Thanks

The key is  in this path, '../' is Global path, I use './' to replase it
You can manually set the wrong path,
for me, I change one code at coco.py(db/coco.py)
File "coco.py", line 19, I add"data_dir = './data', and then it's OK
or just 'data' is OK

**Comment by KelvinHuang666** [comment]
config/CenterNet-104.json
"data_dir": "../data"-->"data_dir": "./data" according to
It works,thanks a lot.
