### ISSUE TITLE
indexerror

### ISSUE THREAD

**Issue by czy112** [Duankaiwen/CenterNet#127]
Loaded train 3825 samples
Starting training...
ctdet/headfile_name:1400521.jpg
E:\CenterNet\src\lib\..\..\data\hand\images\1400521.jpg
20190000268
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "E:\CenterNet\src\lib\trains\base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "E:\CenterNet\src\lib\trains\base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "F:\ana\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "F:\ana\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "E:\CenterNet\src\lib\datasets\sample\ctdet.py", line 126, in __getitem__
    draw_gaussian(hm[cls_id], ct_int, radius)
IndexError: index 1 is out of bounds for axis 0 with size 1

how to solove this?
plsease

**Comment by zuzi2015** [comment]
怎么解决的，我也遇到了
IndexError: index 0 is out of bounds for axis 0 with size 0
