### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Wickked-swag** [Duankaiwen/CenterNet#137]
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from nnet.py_factory import NetworkFactory
  File "/home/wickked/Net/CenterNet/nnet/py_factory.py", line 8, in <module>
    from models.py_utils.data_parallel import DataParallel
  File "/home/wickked/Net/CenterNet/models/py_utils/__init__.py", line 6, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/home/wickked/Net/CenterNet/models/py_utils/_cpools/__init__.py", line 8, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/wickked/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
When I use ldd -r to see what symbol is undefined:
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from nnet.py_factory import NetworkFactory
  File "/home/wickked/Net/CenterNet/nnet/py_factory.py", line 8, in <module>
    from models.py_utils.data_parallel import DataParallel
  File "/home/wickked/Net/CenterNet/models/py_utils/__init__.py", line 6, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/home/wickked/Net/CenterNet/models/py_utils/_cpools/__init__.py", line 8, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/wickked/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
Can u help me?Thank u very much

**Comment by NikhilChowdary-MCW** [comment]
Hi @Wickked-swag , did that import error was solved? Please let me know. Thank you.
