### ISSUE TITLE
undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by Prajwal-Gupta** [Duankaiwen/CenterNet#144]
I get this error when I try to run `python train.py CenterNet-52`
```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from nnet.py_factory import NetworkFactory
  File "/home/prajwal/CenterNet/nnet/py_factory.py", line 8, in <module>
    from models.py_utils.data_parallel import DataParallel
  File "/home/prajwal/CenterNet/models/py_utils/__init__.py", line 6, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/home/prajwal/CenterNet/models/py_utils/_cpools/__init__.py", line 8, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/prajwal/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

Any solution for this?

**Comment by YufZh** [comment]
I met the same problem as you, did you solve it?
