### ISSUE TITLE
why No such file or directory？

### ISSUE THREAD

**Issue by lifeiwen** [Duankaiwen/CenterNet#26]
(CenterNet) lf@110:~/CenterNet/CenterNet$ python train.py CenterNet-104
loading all datasets...
using 4 threads
loading from cache file: cache/coco_trainval2014.pkl
No cache file found...
loading annotations into memory...
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "train.py", line 193, in <listcomp>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "/home/lf/CenterNet/CenterNet/db/coco.py", line 66, in __init__
    self._load_data()
  File "/home/lf/CenterNet/CenterNet/db/coco.py", line 75, in _load_data
    self._extract_data()
  File "/home/lf/CenterNet/CenterNet/db/coco.py", line 102, in _extract_data
    self._coco    = COCO(self._label_file)
  File "data/coco/PythonAPI/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '../data/coco/annotations/instances_trainval2014.json'

**Comment by liuzehao** [comment]
config/CenterNet-104.json
`"data_dir": "../data"-->"data_dir": "./data"` according to
https://blog.csdn.net/liu506039293/article/details/89525765

**Comment by lifeiwen** [comment]
@liuzehao 谢谢，请问您知道在test的时候
loading model from cache/nnet/CenterNet-104/CenterNet-104_480000.pkl
locating kps:   0%|                                   | 0/20288 [00:00<?, ?it/s]
kps是什么意思？
