### ISSUE TITLE
python train.py

### ISSUE THREAD

**Issue by wudi00** [Duankaiwen/CenterNet#34]
when I use `python train.py CenterNet-104` to train the model, there is such error
`Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/media/disk/wudi/CenterNet/sample/coco.py", line 200, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/media/disk/wudi/CenterNet/sample/coco.py", line 100, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/media/disk/wudi/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'`
whe does the error happen? how to avoid this error? Thanks

**Comment by Duankaiwen** [comment]
@wudi00 Hi, I think your trainval2014 dataset may not contain the 5k images in val2014.zip. The trainval2014 dataset consists of all images in train2014.zip and 35k images in val2014.zip for training. You can copy all images in val2014.zip to train2014 and rename it as trainval2014.

**Comment by wudi00** [comment]
@Duankaiwen Thanks. But Another question occured, `RuntimeError: Expected the device associated with the stream at index 1 (was 0) to match the device supplied at that index (expected 26552) (scatter at /opt/conda/conda-bld/pytorch_1544174967633/work/torch/csrc/cuda/comm.cpp:199)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7ff6204a8cc5 in /opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<at::cuda::CUDAStream>, std::allocator<c10::optional<at::cuda::CUDAStream> > > > const&) + 0x85d (0x7ff61883d5cd in /opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x4f9ee1 (0x7ff618842ee1 in /opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x111e36 (0x7ff61845ae36 in /opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #14: THPFunction_apply(_object*, _object*) + 0x5dd (0x7ff61865640d in /opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)


terminate called without an active exception
Aborted (core dumped)
` , why? and how to seal with it? Thanks a lot.

**Comment by wudi00** [comment]
@Duankaiwen What version of g++ is required to compile c++ files?

**Comment by wudi00** [comment]
@Duankaiwen Hi, I want to train my dataset, and where shouled I modify in the code?

**Comment by nuist-xinyu** [comment]
hi，i have the same problem。 how do you solve it？

**Comment by wudi00** [comment]
The solution follows the answers given by the author above

**Comment by wudi00** [comment]
@nuist-xinyu The solution follows the answers given by the author above

**Comment by nuist-xinyu** [comment]
is your download the trainval2014  and val2014 from author given?

**Comment by nuist-xinyu** [comment]
What is the version of your cuda?

**Comment by wudi00** [comment]
Yes, I download the trainval2014 and val2014 according to the readme. 
I use cuda 10.0

**Comment by nuist-xinyu** [comment]
I have the same problem with you.
but whatever i choose cuda9 or 10 ，still don‘t training

**Comment by wudi00** [comment]
Check the file path again， The trainval2014 dataset consists of all images in train2014.zip and 35k images in val2014.zip for training.

**Comment by nuist-xinyu** [comment]
I downloaded the training set and validation set from the address given by the author and merged them together. Can you tell me how big your training set is?

**Comment by nuist-xinyu** [comment]
123,287 项，共 20.1 GB
this is mine

**Comment by wudi00** [comment]
You can copy all images in val2014.zip to train2014 and rename it as trainval2014.

**Comment by nuist-xinyu** [comment]
Friends, do you mind giving me your training set?

**Comment by nuist-xinyu** [comment]
I just copied the image in the verification set directly to the training set.

**Comment by wudi00** [comment]
sorry, my data is not in my computer. copy all images in val2014.zip to train2014 and rename it as trainval2014.

**Comment by nuist-xinyu** [comment]
ok  thank you

**Comment by nuist-xinyu** [comment]
What version of graphics card do you use?

**Comment by frvmsv** [comment]
> @wudi00 Hi, I think your trainval2014 dataset may not contain the 35k images in val2014.zip. The trainval2014 dataset consists of all images in train2014.zip and 35k images in val2014.zip for training. You can copy all images in val2014.zip to train2014 and rename it as trainval2014.

i do this but still i get this error.how can i solve it?
