### ISSUE TITLE
Iteration stop updating unexpectedly in training

### ISSUE THREAD

**Issue by sherlockedlee** [Duankaiwen/CenterNet#36]
Thank you for your brilliant work and code.I was training on my own datasets which is format in the same format as coco,the place I made some slight changes is the 'categories' and 'outdim',and adjust the batch size.It works well at the beginning of training,but iteration stop updating after several steps.There are no errors at the very beginning.But after I recreating the environment,some errors occur,like
'
```
File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "../CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "../CenterNet/sample/coco.py", line 169, in kp_detection
    tl_regrs[b_ind, tag_ind, :]  = [fxtl - xtl, fytl - ytl]
IndexError: index 128 is out of bounds for axis 1 with size 128
Process Process-4:
Traceback (most recent call last):
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "../CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "../PycharmProjects/CenterNet/sample/coco.py", line 169, in kp_detection
    tl_regrs[b_ind, tag_ind, :]  = [fxtl - xtl, fytl - ytl]
IndexError: index 128 is out of bounds for axis 1 with size 128
  2%| | 1048/48000 [12:19<9:12:11,  1.42it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "../.conda/envs/CenterNet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "../.conda/envs/CenterNet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 51, in pin_memory
    data = data_queue.get()
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "../.conda/envs/CenterNet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "../.conda/envs/CenterNet/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

training loss at iteration 1050: 8.643182754516602
focal loss at iteration 1050:    8.27330493927002
pull loss at iteration 1050:     0.02936428226530552
push loss at iteration 1050:     0.1124843955039978
regr loss at iteration 1050:     0.2280292809009552
training loss at iteration 1055: 10.512767791748047
focal loss at iteration 1055:    10.169354438781738
pull loss at iteration 1055:     0.014561626128852367
push loss at iteration 1055:     0.06111855432391167
regr loss at iteration 1055:     0.2677331566810608
  2%| | 1055/48000 [12:24<9:12:05,  1.42it/s]
```
'
and freeze at this step.The project is still running on GPU when I watch in terminal.
Could anybody tell me how to fix it?Thanks for your patience.

**Comment by sherlockedlee** [comment]
solved already.

**Comment by wudi00** [comment]
@sherlockedlee Hi，I want to use my own dataset, and I modified some tips, first format the data in the same format as coco, change the input size and output size, change the `self._cat_ids` in the ./db/coco.py, and anywhere else should I change? thanks

**Comment by sherlockedlee** [comment]
@wudi00 You should modify the `"categories"` in centernet-52/104.json and detection.py in line 8.

**Comment by wudi00** [comment]
@sherlockedlee Thankes. I have already modified the two points,
1. And anywhere else?
2.What does the files in ./cache/coco_trainval2014.pkl mean? Does it need to be modified?

**Comment by sherlockedlee** [comment]
@wudi00 1.I can't remember clearly.All work seems to be done.
2.It's your model,you can't modify pickle files.You can use following code to check these files.
```
# -*- coding: UTF8 -*-
f = open('./CenterNet/cache/coco_train2014.pkl','rb')
data = pickle.load(f)
print(data)
```

**Comment by yzhu20** [comment]
I have met the same problem with this!!!! Could you please teach me how to solve this bug?

**Comment by RenAihua** [comment]
@sherlockedlee ,hello, i meet the same problem, can you tell me how can i solve it, thanks!

**Comment by RenAihua** [comment]
@sherlockedlee ,I have got it ,thanks!

**Comment by billyzju** [comment]
@sherlockedlee @RenAihua Hey, guys! How did you solve this problem?! I encountered the same problem and have tried methods you guys mentioned, didn't work for me!

**Comment by RenAihua** [comment]
@billyzju https://github.com/princeton-vl/CornerNet/issues/26  hey, you can try in this way

**Comment by billyzju** [comment]
> @billyzju [princeton-vl/CornerNet#26](https://github.com/princeton-vl/CornerNet/issues/26) hey, you can try in this way

Thanks a lot! Seems work for me! It's object number out of bounds
