### ISSUE TITLE
train error!!!

### ISSUE THREAD

**Issue by zhepherd** [Duankaiwen/CenterNet#41]
thx for your code,  but i have got the error when training ,stop at 
![image](https://user-images.githubusercontent.com/3793108/58313766-e8c8ef00-7e40-11e9-96e7-02ba948a4911.png) 
what happened ?

**Comment by zhepherd** [comment]
@Duankaiwen

**Comment by nuist-xinyu** [comment]
this error the same to me 
please tell me how to resolve it  
thank you

**Comment by Duankaiwen** [comment]
what's your torch version and  gcc  version?

**Comment by zhepherd** [comment]
@Duankaiwen 
torch is 0.4.1
![image](https://user-images.githubusercontent.com/3793108/58608182-ffee5d80-82d4-11e9-83a8-c9e71dfdcff1.png)

**Comment by Duankaiwen** [comment]
Does the original code work in your own computer?

**Comment by zhepherd** [comment]
no , because i had download the coco images before and  the image is too big, so i use the images which i download before and use your json file . ,but have the error 
![image](https://user-images.githubusercontent.com/3793108/58617152-fcb59a80-82f1-11e9-8269-1fa6e51f9a2f.png)
your train2014  json file have the val2014 image?

**Comment by zhepherd** [comment]
@Duankaiwen

**Comment by Duankaiwen** [comment]
Try using the gcc 4.9 to recompile the corner pooling layers.

**Comment by ZhenLiuBuaa** [comment]
why the train2014 json file has val2014 image?

**Comment by LETMEY** [comment]
@Duankaiwen I met a similar mistake. gcc version is 5.4.0, i suspect that the training images are not read, but the path of the training images is correct. 
`loading all datasets...
using 4 threads
results/CenterNet-104
label_dir: ./data/coco/annotations/instances_trainval2014.json
image_dir: ./data/coco/images/trainval2014
loading from cache file: cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=14.82s)
creating index...
index created!
results/CenterNet-104
label_dir: ./data/coco/annotations/instances_trainval2014.json
image_dir: ./data/coco/images/trainval2014
loading from cache file: cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=15.99s)
creating index...
index created!
results/CenterNet-104
label_dir: ./data/coco/annotations/instances_trainval2014.json
image_dir: ./data/coco/images/trainval2014
loading from cache file: cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=16.80s)
creating index...
index created!
results/CenterNet-104
label_dir: ./data/coco/annotations/instances_trainval2014.json
image_dir: ./data/coco/images/trainval2014
loading from cache file: cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=15.46s)
creating index...
index created!
results/CenterNet-104
label_dir: ./data/coco/annotations/instances_minival2014.json
image_dir: ./data/coco/images/minival2014
loading from cache file: cache/coco_minival2014.pkl
loading annotations into memory...
Done (t=0.43s)
creating index...
index created!
system config...
{'batch_size': 48,
 'cache_dir': 'cache',
 'chunk_sizes': [6, 6, 6, 6, 6, 6, 6, 6],
 'config_dir': 'config',
 'data_dir': '../data',
 'data_rng': <mtrand.RandomState object at 0x7fd63df035e8>,
 'dataset': 'MSCOCO',
 'decay_rate': 10,
 'display': 5,
 'learning_rate': 0.00025,
 'max_iter': 480000,
 'nnet_rng': <mtrand.RandomState object at 0x7fd63df03630>,
 'opt_algo': 'adam',
 'prefetch_size': 6,
 'pretrain': None,
 'result_dir': 'results',
 'sampling_function': 'kp_detection',
 'snapshot': 5000,
 'snapshot_name': 'CenterNet-104',
 'stepsize': 450000,
 'test_split': 'testdev',
 'train_split': 'trainval',
 'val_iter': 500,
 'val_split': 'minival',
 'weight_decay': False,
 'weight_decay_rate': 1e-05,
 'weight_decay_type': 'l2'}
db config...
{'ae_threshold': 0.5,
 'border': 128,
 'categories': 80,
 'data_aug': True,
 'gaussian_bump': True,
 'gaussian_iou': 0.7,
 'gaussian_radius': -1,
 'input_size': [511, 511],
 'kp_categories': 1,
 'lighting': True,
 'max_per_image': 100,
 'merge_bbox': False,
 'nms_algorithm': 'exp_soft_nms',
 'nms_kernel': 3,
 'nms_threshold': 0.5,
 'output_sizes': [[128, 128]],
 'rand_color': True,
 'rand_crop': True,
 'rand_pushes': False,
 'rand_samples': False,
 'rand_scale_max': 1.4,
 'rand_scale_min': 0.6,
 'rand_scale_step': 0.1,
 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
 'special_crop': False,
 'test_scales': [1],
 'top_k': 70,
 'weight_exp': 8}
len of db: 118287
start prefetching data...
start prefetching data...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-1:
Traceback (most recent call last):
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-2:
Traceback (most recent call last):
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
building model...
module_file: models.CenterNet-104
start prefetching data...
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-3:
Traceback (most recent call last):
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
shuffling indices...
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-5:
Traceback (most recent call last):
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-4:
Traceback (most recent call last):
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/liu608/anaconda3/envs/CenterNet/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/liu608/桌面/CenterNet/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/liu608/桌面/CenterNet/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
total parameters: 210062960
setting learning rate to: 0.00025
training start...
  0%|                                                | 0/480000 [00:00<?, ?it/s]
`

**Comment by kauravin** [comment]
@Duankaiwen Thanks for the amazing work! I have been able to run your code as instructed on the COCO dataset and run some experiments on it successfully. However on my own dataset (formatted in COCO style), it starts the training, however it just stops abruptly, with no error or warning. I'm unable to debug this. gcc version is 5.4.0, Ubuntu 18.04 and PyTorch is 1.0.0. Here's what the screen looks like: 

![train_error_cnet](https://user-images.githubusercontent.com/25163986/69753297-1b151b00-1108-11ea-818e-86d3ac1c6fcb.png)
