### ISSUE TITLE
train error!!!!help help help !!!help me

### ISSUE THREAD

**Issue by nuist-xinyu** [Duankaiwen/CenterNet#45]
File "/home/xinyu/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/xinyu/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/xinyu/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/xinyu/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-4:
Traceback (most recent call last):
  File "/home/xinyu/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/xinyu/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 47, in prefetch_data
    raise e
  File "train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/home/xinyu/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/home/xinyu/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
total parameters: 210062960
setting learning rate to: 0.00025
training start...
  0%|                                                | 0/480000 [00:00<?, ?it/s]

**Comment by Duankaiwen** [comment]
Hi, @nuist-xinyu. I think your trainval2014 dataset may not contain the 35k images in val2014.zip. The trainval2014 dataset consists of all images in train2014.zip and 35k images in val2014.zip for training. You can copy all images in val2014.zip to train2014 and rename it as trainval2014.

**Comment by Lixia1221** [comment]
Following instructions, execution is still the same error
