### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by wfchenwf** [Duankaiwen/CenterNet#53]
(py36) PS D:\pythoncode\CenterNet_pytorch_win10_cuda10_py3.68\CenterNet> python test.py CenterNet-104 --testiter 480000

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    from nnet.py_factory import NetworkFactory
  File "D:\pythoncode\CenterNet_pytorch_win10_cuda10_py3.68\CenterNet\nnet\py_factory.py", line 19, in <module>
    from models.py_utils.data_parallel import DataParallel
  File "D:\pythoncode\CenterNet_pytorch_win10_cuda10_py3.68\CenterNet\models\py_utils\__init__.py", line 6, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "D:\pythoncode\CenterNet_pytorch_win10_cuda10_py3.68\CenterNet\models\py_utils\_cpools\__init__.py", line 8, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: DLL load failed: 找不到指定的程序。

请问这个是什么原因啊？

**Comment by Duankaiwen** [comment]
Sorry, i don't know how to run this code in windows. Maybe this can be helpful: https://github.com/Duankaiwen/CenterNet/issues/33
