### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by xuanthuyvo** [Duankaiwen/CenterNet#68]
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
loading all datasets...
using 1 threads
loading from cache file: /content/CenterNet-master/cache/coco_trainval2014.pkl
loading annotations into memory...
Done (t=14.72s)
creating index...
index created!
loading from cache file: /content/CenterNet-master/cache/coco_minival2014.pkl
loading annotations into memory...
Done (t=0.39s)
creating index...
index created!
system config...
{'batch_size': 8,
 'cache_dir': '/content/CenterNet-master/cache',
 'chunk_sizes': [1, 1, 1, 1, 1, 1, 1, 1],
 'config_dir': '/content/CenterNet-master/config',
 'data_dir': '/content/CenterNet-master/data',
 'data_rng': <mtrand.RandomState object at 0x7f01f344f798>,
 'dataset': 'MSCOCO',
 'decay_rate': 10,
 'display': 5,
 'learning_rate': 0.00025,
 'max_iter': 4800,
 'nnet_rng': <mtrand.RandomState object at 0x7f01f344f7e0>,
 'opt_algo': 'adam',
 'prefetch_size': 1,
 'pretrain': None,
 'result_dir': '/content/CenterNet-master/results',
 'sampling_function': 'kp_detection',
 'snapshot': 50,
 'snapshot_name': 'CenterNet-104',
 'stepsize': 4800,
 'test_split': 'testdev',
 'train_split': 'trainval',
 'val_iter': 500,
 'val_split': 'minival',
 'weight_decay': False,
 'weight_decay_rate': 1e-05,
 'weight_decay_type': 'l2'}
db config...
{'ae_threshold': 0.5,
 'border': 128,
 'categories': 80,
 'data_aug': True,
 'gaussian_bump': True,
 'gaussian_iou': 0.7,
 'gaussian_radius': -1,
 'input_size': [511, 511],
 'kp_categories': 1,
 'lighting': True,
 'max_per_image': 100,
 'merge_bbox': False,
 'nms_algorithm': 'exp_soft_nms',
 'nms_kernel': 3,
 'nms_threshold': 0.5,
 'output_sizes': [[128, 128]],
 'rand_color': True,
 'rand_crop': True,
 'rand_pushes': False,
 'rand_samples': False,
 'rand_scale_max': 1.4,
 'rand_scale_min': 0.6,
 'rand_scale_step': 0.1,
 'rand_scales': array([0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3]),
 'special_crop': False,
 'test_scales': [1],
 'top_k': 70,
 'weight_exp': 8}
len of db: 118287
start prefetching data...
start prefetching data...
building model...
module_file: models.CenterNet-104
shuffling indices...
shuffling indices...
Traceback (most recent call last):
  File "/content/CenterNet-master/train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/content/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/content/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/content/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/CenterNet-master/train.py", line 47, in prefetch_data
    raise e
  File "/content/CenterNet-master/train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/content/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/content/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/content/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/content/CenterNet-master/train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/content/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/content/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/content/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/CenterNet-master/train.py", line 47, in prefetch_data
    raise e
  File "/content/CenterNet-master/train.py", line 43, in prefetch_data
    data, ind = sample_data(db, ind, data_aug=data_aug)
  File "/content/CenterNet-master/sample/coco.py", line 199, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind, data_aug, debug)
  File "/content/CenterNet-master/sample/coco.py", line 99, in kp_detection
    image, detections = random_crop(image, detections, rand_scales, input_size, border=border)
  File "/content/CenterNet-master/sample/utils.py", line 57, in random_crop
    image_height, image_width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
total parameters: 210062960
setting learning rate to: 0.00025

**Comment by Duankaiwen** [comment]
@xuanthuyvo Hi, see this: https://github.com/Duankaiwen/CenterNet/issues/45

**Comment by xuanthuyvo** [comment]
@Duankaiwen Thank you for your response. I will try to replace again.
