### ISSUE TITLE
When training on my datasets, some problems ocurred

### ISSUE THREAD

**Issue by Anamzing** [Duankaiwen/CenterNet#71]
Here 's some details

  0%|                                                | 0/480000 [00:26<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 141, in train
    training_loss, focal_loss, pull_loss, push_loss, regr_loss = nnet.train(**training)
  File "/home/lry/CenterNet/nnet/py_factory.py", line 82, in train
    loss_kp = self.network(xs, ys)
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lry/CenterNet/models/py_utils/data_parallel.py", line 70, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lry/CenterNet/models/py_utils/data_parallel.py", line 80, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lry/CenterNet/nnet/py_factory.py", line 20, in forward
    preds = self.model(*xs, **kwargs)
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lry/CenterNet/nnet/py_factory.py", line 32, in forward
    return self.module(*xs, **kwargs)
  File "/usr/local/anaconda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lry/CenterNet/models/py_utils/kp.py", line 296, in forward
    return self._train(*xs, **kwargs)
  File "/home/lry/CenterNet/models/py_utils/kp.py", line 198, in _train
    print("cr_inds          ",xs[3])
IndexError: tuple index out of range

**Comment by Anamzing** [comment]
there are only 3 parts in xs[3], what should i do

**Comment by Duankaiwen** [comment]
@Anamzing Please check your 'sample/coco.py'
