### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by ruinianxu** [Duankaiwen/CenterNet#76]
Hi all,
I am trying to train CenterNet on my own dataset with coco format. I got the following error during training process.
Traceback (most recent call last):
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/train.py", line 205, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/train.py", line 138, in train
    training_loss, focal_loss, pull_loss, push_loss, regr_loss = nnet.train(**training)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/nnet/py_factory.py", line 82, in train
    loss_kp = self.network(xs, ys)
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/models/py_utils/data_parallel.py", line 68, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/train.py", line 54, in pin_memory
    data["ys"] = [y.pin_memory() for y in data["ys"]]
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/train.py", line 54, in <listcomp>
    data["ys"] = [y.pin_memory() for y in data["ys"]]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/THCCachingHostAllocator.cpp:271

    result = self.forward(*input, **kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/nnet/py_factory.py", line 20, in forward
    preds = self.model(*xs, **kwargs)
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/nnet/py_factory.py", line 32, in forward
    return self.module(*xs, **kwargs)
  File "/home/ruinianxu/miniconda2/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/models/py_utils/kp.py", line 289, in forward
    return self._train(*xs, **kwargs)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/models/py_utils/kp.py", line 227, in _train
    tl_regr = _tranpose_and_gather_feat(tl_regr, tl_inds)
  File "/home/ruinianxu/IVA_Lab/Project/CenterNet-master/models/py_utils/kp_utils.py", line 59, in _tranpose_and_gather_feat
    feat = feat.permute(0, 2, 3, 1).contiguous()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/THCTensorCopy.cu:206
terminate called after throwing an instance of 'at::Error'
  what():  CUDA error: invalid device pointer (CudaCachingDeleter at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/THCCachingAllocator.cpp:498)
The only diffence I made for installation is I didn't conda install cudatoolkit since my local cuda is 8.0. 
Really appreciate it if anybody can give me some hints about this error.

**Comment by ruinianxu** [comment]
I think the problem came from cudatoolkit. I removed the env and reinstalled it fully followed by the instruction. It worked.
