### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wudi00** [Duankaiwen/CenterNet#84]
When I train on my own dataset there is such error
`Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 150, in train
    training_loss, focal_loss, pull_loss, push_loss, regr_loss = nnet.train(**training)
  File "/media/disk/wudi/CenterNet/nnet/py_factory.py", line 89, in train
    loss_kp = self.network(xs, ys)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/models/py_utils/data_parallel.py", line 68, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/nnet/py_factory.py", line 22, in forward
    preds = self.model(*xs, **kwargs)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/nnet/py_factory.py", line 34, in forward
    return self.module(*xs, **kwargs)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/models/py_utils/kp.py", line 289, in forward
    return self._train(*xs, **kwargs)
  File "/media/disk/wudi/CenterNet/models/py_utils/kp.py", line 217, in _train
    tl_cnv = tl_cnv_(cnv)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/models/CenterNet-52.py", line 34, in forward
    look_right   = self.pool2(look_conv1)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/disk/wudi/CenterNet/models/py_utils/_cpools/__init__.py", line 72, in forward
    return LeftPoolFunction.apply(x)
  File "/media/disk/wudi/CenterNet/models/py_utils/_cpools/__init__.py", line 39, in forward
    output = left_pool.forward(input)[0]
RuntimeError: coalesce not supported on CUDAFloatType (coalesce at /pytorch/build/aten/src/ATen/CUDAFloatType.cpp:6232)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f0de3e75021 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f0de3e748ea in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: at::CUDAFloatType::coalesce(at::Tensor const&) const + 0x60 (0x7f0d40265e10 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: torch::autograd::VariableType::coalesce(at::Tensor const&) const + 0x228 (0x7f0dd317fb88 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: at::native::_sparse_sum(at::Tensor const&, c10::ScalarType) + 0x30 (0x7f0d359d7250 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #5: at::TypeDefault::_sparse_sum(at::Tensor const&, c10::ScalarType) const + 0x5d (0x7f0d35b69f5d in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: torch::autograd::VariableType::_sparse_sum(at::Tensor const&, c10::ScalarType) const + 0x139 (0x7f0dd3114c29 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: pool_forward(at::Tensor) + 0x38 (0x7f0dcb5721f8 in /media/disk/wudi/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/left_pool.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x1510c (0x7f0dcb57f10c in /media/disk/wudi/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/left_pool.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x13585 (0x7f0dcb57d585 in /media/disk/wudi/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/left_pool.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #16: THPFunction_apply(_object*, _object*) + 0x581 (0x7f0ddad0bab1 in /media/disk/wudi/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)`
I have modefied the batch size and chunk_sizes in config.py, but it doesn't work.

**Comment by Duankaiwen** [comment]
@wudi00  What's your pytorch version?

**Comment by wudi00** [comment]
My torch version is pytorch 1.0.
It can be trained now, but the loss maybe 0 sometimes.
`training loss at iteration 32650: 1.8800256252288818
focal loss at iteration 32650:    1.8800256252288818
pull loss at iteration 32650:     0.0
push loss at iteration 32650:     0.0
regr loss at iteration 32650:     0.0
`

**Comment by surserrr** [comment]
@wudi00  I meet the same problem .How do you solve it?
