### ISSUE TITLE
ModuleNotFoundError: No module named 'models.CenterNet-104-multi_scale'

### ISSUE THREAD

**Issue by mochechan** [Duankaiwen/CenterNet#85]
How to train the CenterNet-104-multi_scale? Is the following command correct or not?

`python train.py CenterNet-104-multi_scale`

When I attempting to train the CenterNet-104-multi_scale, the following error occurs.

```
module_file: models.CenterNet-104-multi_scale
Traceback (most recent call last):
  File "train.py", line 203, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 115, in train
    nnet = NetworkFactory(training_dbs[0])
  File "/data/201909lpr/restful/centernet/CenterNet/nnet/py_factory.py", line 40, in __init__
    nnet_module = importlib.import_module(module_file)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.CenterNet-104-multi_scale'
```
What is the correct command? Thanks a lot.

**Comment by Duankaiwen** [comment]
@mochechan Just 'python train.py CenterNet-104'. 'CenterNet-104-multi_scale' is for multi-scale testing
