### ISSUE TITLE
why the pull loss and push loss is 0.0 when training my own dataset?

### ISSUE THREAD

**Issue by yushanshan05** [Duankaiwen/CenterNet#86]
When I train my own dataset, the pull loss and push loss is always 0.0. The log is:
training loss at iteration 270: 0.08008845895528793
focal loss at iteration 270:    0.08008845895528793
pull loss at iteration 270:     0.0
push loss at iteration 270:     0.0
regr loss at iteration 270:     0.0
training loss at iteration 275: 0.07004862278699875
focal loss at iteration 275:    0.07004862278699875
pull loss at iteration 275:     0.0
push loss at iteration 275:     0.0
regr loss at iteration 275:     0.0
training loss at iteration 280: 0.06663033366203308
focal loss at iteration 280:    0.06663033366203308
pull loss at iteration 280:     0.0
push loss at iteration 280:     0.0
regr loss at iteration 280:     0.0
training loss at iteration 285: 0.07438242435455322
focal loss at iteration 285:    0.07438242435455322
pull loss at iteration 285:     0.0
push loss at iteration 285:     0.0
regr loss at iteration 285:     0.0

It seems something error!
After, I test the model,there is also some errors like this:

Traceback (most recent call last):
File "test.py", line 99, in
test(testing_db, args.split, args.testiter, args.debug, args.suffix)
File "test.py", line 61, in test
testing(db, nnet, result_dir, debug=debug)
File "/home/lz/python/CenterNet/CenterNet-master/test/coco.py", line 321, in testing
return globals()[system_configs.sampling_function](db, nnet, result_dir, debug=debug)
File "/home/lz/python/CenterNet/CenterNet-master/test/coco.py", line 317, in kp_detection
db.evaluate(result_json, cls_ids, image_ids)
File "/home/lz/python/CenterNet/CenterNet-master/db/coco.py", line 176, in evaluate
coco_dets = coco.loadRes(result_json)
File "data/coco/PythonAPI/pycocotools/coco.py", line 318, in loadRes
if 'caption' in anns[0]:
IndexError: list index out of range

Can anyone help me?Thanks a lot!!!

**Comment by yushanshan05** [comment]
> When I train my own dataset, the pull loss and push loss is always 0.0. The log is:
> training loss at iteration 270: 0.08008845895528793
> focal loss at iteration 270: 0.08008845895528793
> pull loss at iteration 270: 0.0
> push loss at iteration 270: 0.0
> regr loss at iteration 270: 0.0
> training loss at iteration 275: 0.07004862278699875
> focal loss at iteration 275: 0.07004862278699875
> pull loss at iteration 275: 0.0
> push loss at iteration 275: 0.0
> regr loss at iteration 275: 0.0
> training loss at iteration 280: 0.06663033366203308
> focal loss at iteration 280: 0.06663033366203308
> pull loss at iteration 280: 0.0
> push loss at iteration 280: 0.0
> regr loss at iteration 280: 0.0
> training loss at iteration 285: 0.07438242435455322
> focal loss at iteration 285: 0.07438242435455322
> pull loss at iteration 285: 0.0
> push loss at iteration 285: 0.0
> regr loss at iteration 285: 0.0
> 
> It seems something error!
> After, I test the model,there is also some errors like this:
> 
> Traceback (most recent call last):
> File "test.py", line 99, in
> test(testing_db, args.split, args.testiter, args.debug, args.suffix)
> File "test.py", line 61, in test
> testing(db, nnet, result_dir, debug=debug)
> File "/home/lz/python/CenterNet/CenterNet-master/test/coco.py", line 321, in testing
> return globals()[system_configs.sampling_function](db, nnet, result_dir, debug=debug)
> File "/home/lz/python/CenterNet/CenterNet-master/test/coco.py", line 317, in kp_detection
> db.evaluate(result_json, cls_ids, image_ids)
> File "/home/lz/python/CenterNet/CenterNet-master/db/coco.py", line 176, in evaluate
> coco_dets = coco.loadRes(result_json)
> File "data/coco/PythonAPI/pycocotools/coco.py", line 318, in loadRes
> if 'caption' in anns[0]:
> IndexError: list index out of range
> 
> Can anyone help me?Thanks a lot!!!

**Comment by Duankaiwen** [comment]
Can I see your full log?

**Comment by Troy0425** [comment]
I have the same problem!

**Comment by Troy0425** [comment]
This is my log. Thank you
[log.txt](https://github.com/Duankaiwen/CenterNet/files/3549641/log.txt)

**Comment by Troy0425** [comment]
I think the problem is associated with  the annotations file

**Comment by Troy0425** [comment]
I have figured out the problem. It's because the boxes ids of my annotations file are all the same.

**Comment by Duankaiwen** [comment]
@Troy0425 Great!

**Comment by Dawnlnz** [comment]
Have you sloved the problem? I have the same problem with you, and  I am sure that the boxes ids of my annotation file are different. Can you help me?

**Comment by kauravin** [comment]
@Troy0425 I have a question with respect to the box_ids. Each individual dict in the annotations object is of this format: 
 bb_dict = {
                    'segmentation': [],
                    'area': area_bb,
                    'iscrowd': 0,
                    'image_id': image_id,
                    'bbox': bb_coords,
                    'category_id': category_id, 
                    'id': annotation_id
                }
If for a given annotation mask, there are 10 bounding boxes, then I'm assuming (from COCO's structure) there would be 10 such dictionaries. However, all these 10 dictionaries share the same 'id' (annotation ID) which is unique for the given mask. Is my understanding correct? I also occasionally see 0 push, pull losses on my own dataset. Please let me know what you think.

**Comment by qianqianderizi** [comment]
> I have figured out the problem. It's because the boxes ids of my annotations file are all the same.

what are boxes ids?
